Document: mingw-w64-expat
Title: Debian mingw-w64-expat Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-expat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-expat/mingw-w64-expat.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-expat/mingw-w64-expat.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-expat/mingw-w64-expat.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-expat/html/index.html
Files: /usr/share/doc/mingw-w64-expat/html/*.html
